### ISSUE TITLE
Training data origins

### ISSUE THREAD

**Issue by JulienBrochier** [oliverguhr/spelling#1]
Thank you for sharing this project. The already trained English model works really well!

I'm working on a version for French language.

I have some questions about wiki.en.train.csv and wiki.en.test.csv files needed in combine.sh.
I would like to know where you got them and if they could be replaced by taking a larger .txt Wikipedia dump.    
Ex: eng_news_2020_300K-sentences instead of 100k?

Also, mentioning the [Leipzig corpora website](https://corpora.uni-leipzig.de) in "Possible Datasets" could help finding files for other languages.

**Comment by oliverguhr** [comment]
Hi @JulienBrochier 
thanks for your interest. I got both, the "wiki" and the "news" dataset  from the Leipzig corpora website. They crawled websites and provide datasets with extracted sentences from these websites. The "wiki" data set contains sentences from Wikipedia, the  "news"  data set consists of sentences from different news websites. You can download  datasets with french sentences from here: https://wortschatz.uni-leipzig.de/en/download/French

I would love to hear how your experiments are going.

**Comment by JulienBrochier** [comment]
Hi @oliverguhr,
My question was about .csv files mentioned in combine.sh.
I will keep you up to date about my experiments.

**Comment by oliverguhr** [comment]
@JulienBrochier The "how to" was actually wrong. You need to run the "convert_leipzig_data.sh" first. This processes one or more files from the leipzig corpora and write it into one file. This single file gets then processed by "generate_dataset.py" which will do the data augmentation and create the csv files for the training. The "[combine.sh](https://github.com/oliverguhr/spelling/blob/main/combine.sh)" is only needed if you like to combine multiple languages to train multilingual models. 

I fixed this in readme. Thanks for the hint :)
