### ISSUE TITLE
You hugging face shared model produces different results at my end

### ISSUE THREAD

**Issue by michiruf** [oliverguhr/spelling#4]
Hi there,

since my graphics card is pretty slow, I started playing around with your hugging face provided version of the german and english models. If I go for the most minimalistic approach, I get different behaviours when using the english or german version.

**Inputs (for both variants):**
Input 1: `das idst ein neuZr test`
Input 2: `Well maybler ill just write as fast as i can to get this thing stugglinh`

**German results:**
Result 1: `[{'generated_text': 'Das ist ein neuer Test. Das ist ein neuer Test. Das ist ein neuer Test. Das'}]`
Result 2: `[{'generated_text': 'Will maybler will just write as fast as is can to get this thing st'}]`

**English results:**
Result 1: `[{'generated_text': 'As idest in near test.'}]`
Result 2: `[{'generated_text': "Well, maybe I'll just write as fast as I can to get this thing stuck"}]`

**Code to reproduce:**
```python
from transformers import pipeline
fix_spelling = pipeline("text2text-generation", model="oliverguhr/spelling-correction-english-base")
# fix_spelling = pipeline("text2text-generation", model="oliverguhr/spelling-correction-german-base")
print(fix_spelling("das idst ein neuZr test"))
print(fix_spelling("Well maybler ill just write as fast as i can to get this thing stugglinh"))
```

Am I doing something completely wrong here? Do you have some insights on why this might be? Sounds pretty strange to me, that these 2 variants differ in the length of the results they present, but I am totally new to this.

Thanks alot for your awesome work,
Michiruf

**Comment by oliverguhr** [comment]
Hi @michiruf,
thanks for the feedback. So, the English model works only for English and the German model only for German. I tried to train a multilingual model as well, but did not publish it yet. 

I guess we see here different behavior because the German model is based on flan T5 and the English model is based on Bart. The repetition is a strange glitch that I observed as well. Sometimes you get rid of it by simply setting the "max_length" property like this:

```python
from transformers import pipeline
fix_spelling = pipeline("text2text-generation", model="oliverguhr/spelling-correction-german-base")
print(fix_spelling("das idst ein neuZr test",max_length=50))
```

**Comment by michiruf** [comment]
Hi,

I thought that aswell, I just wanted to point out the difference in the length of the response is consistently to these variants. You got any estimate when you will publish this?

In your repo here, I could train a Bart based model with german. Is there any version available for this already trained model?

Im currently trying to develop a text to speech overlay for people that are speechless and really want to get a spelling correction going.

Cheers

**Comment by oliverguhr** [comment]
I did train some mbart models for German, but back then I had only access to slow GPUs so stopped working on that before I got any results. I look into the multilingual models the next days and see if I can find something useful. 

Until then, can you use the current German model for your use case?

**Comment by oliverguhr** [comment]
I found the issue! To fix the text repetition issue, you need to add the task prefix. This prefix "correct: " in my case. I forgot to add this to the documentation. 

This code should work as expected:
```python
from transformers import pipeline
fix_spelling = pipeline("text2text-generation", model="oliverguhr/spelling-correction-german-base")
print(fix_spelling("correct: das idst ein neuZr test"))
```

However, I also uploaded a multilingual (DE and EN) for you to test. The multilingual version uses a shorter "fix:" prefix to save a few tokens.
https://huggingface.co/oliverguhr/spelling-correction-multilingual-base

**Comment by michiruf** [comment]
Awesome stuff, thanks!
Ill definetly have a look at those

**Comment by oliverguhr** [comment]
Let me know how this works for you
