### ISSUE TITLE
Spell Correction sequence issue with BART based Model

### ISSUE THREAD

**Issue by lalitaa** [oliverguhr/spelling#5]
Hey Oliver,

I used this hugging face model oliverguhr/spelling-correction-english-base. i fine-tuned this on my own data(medical data). But i have observed that BART messes up with the input sequence.  For example.
I need to consult a Geriatric Psychiatrists inside San Diego --> ['I need to consult a Geriatric Psychiatrists near by San Jose']
I want an opinion from Chiropractic in 90048  --> ['I want an Audio from Cheropractic in 9 January']

Is there any way where i can correct this type of issue and force model to give corrected sentence  in input sequence format? Any help would be highly appreciated..

**Comment by oliverguhr** [comment]
Hey @lalitaa,
how much data did you use to fine-tune the model? In my tests I was able to improve the model behavior by 1) adding more data and 2) by using a less aggressive data augmentation. For example, by increasing the ratio of unaltered texts to 10% ([this line](https://github.com/oliverguhr/spelling/blob/main/generate_dataset.py#L113)).
